@baseUrl = http://localhost:3000/api/v1
@ownerId = 00000000-0000-0000-0000-000000000000
@animalId = 00000000-0000-0000-0000-000000000000
@newOwnerId = 00000000-0000-0000-0000-000000000000

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3Y2JkYTNhOS0wOGUwLTRjN2MtOGJlYS0zNGMwMTY4YmZiYzQiLCJyb2xlIjoiYWRtaW5pc3RyYXRvciIsImlhdCI6MTc3ODA4NzE0OCwiZXhwIjoxNzc4MDkwNzQ4fQ.hSjv3ryXqi4lwwxlkoWSrjMYiGICEoMasFlZ6qyU8RM
### --- ANIMALES (ANIMALS) ---

### Listar todos los animales
GET {{baseUrl}}/animals
Content-Type: application/json
Authorization: Bearer {{token}}

### Registrar nuevo animal
POST {{baseUrl}}/animals
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Firulais",
    "species": "canine",
    "animalType": "urban",
    "breed": "Labrador",
    "gender": "male",
    "birthDate": "2020-05-15",
    "color": "Dorado",
    "ownerId": "{{ownerId}}"
}

### Obtener animal por ID
GET {{baseUrl}}/animals/{{animalId}}
Content-Type: application/json
Authorization: Bearer {{token}}
### Actualizar datos de animal
PUT {{baseUrl}}/animals/{{animalId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Firulais Editado",
    "color": "Blanco con Dorado"
}

### Transferir propiedad del animal
PATCH {{baseUrl}}/animals/{{animalId}}/transfer
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "newOwnerId": "{{newOwnerId}}"
}

### Eliminar animal
DELETE {{baseUrl}}/animals/{{animalId}}
Content-Type: application/json
Authorization: Bearer {{token}}
