@baseUrl = http://localhost:3000/api/v1
@ownerId = e2287a56-623a-4f43-bf2c-fed24687a9a9
@animalId = a89e2959-3b2d-4273-9d66-373a23e9d70f
@newOwnerId = c7878ef4-411e-4112-b517-38f93b4fa19a
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0OWY4MTc1My02MzllLTRjOWQtYmMyNy0xM2I3ZGYzZGJlZDUiLCJyb2xlIjoiYWRtaW5pc3RyYXRvciIsImlhdCI6MTc3OTc2MTA1OSwiZXhwIjoxNzc5NzY0NjU5fQ.lfuEKY7fKsblcQdc9QEL7sXcfs_qU6HLHV2_GAEHT_o

### --- ANIMALES (ANIMALS) ---

### Listar todos los animales
GET {{baseUrl}}/animals
Content-Type: application/json
Authorization: Bearer {{token}}

### Registrar nuevo animal
POST {{baseUrl}}/animals
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Bessie",
    "species": "bovine", 
    "animalType": "rural", 
    "breed": "Holstein",
    "gender": "female", 
    "birthDate": "2020-05-15T00:00:00.000Z",
    "color": "Blanco y Negro",
    "ownerId": "{{ownerId}}"
}




### Obtener animal por ID
GET {{baseUrl}}/animals/{{animalId}}
Content-Type: application/json
Authorization: Bearer {{token}}















### Actualizar datos físicos o estado de animal
PUT {{baseUrl}}/animals/{{animalId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Bessie Editada",
    "color": "Negro Total",
    "breed": "Angus",
    "status": "inactive"
}






### Transferir propiedad del animal a otro dueño
PATCH {{baseUrl}}/animals/{{animalId}}/transfer
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "newOwnerId": "{{newOwnerId}}"
}







### Eliminar animal
DELETE {{baseUrl}}/animals/{{animalId}}
Content-Type: application/json
Authorization: Bearer {{token}}
