@baseUrl = http://localhost:3000/api/v1
@animalId = 0d8a9284-eb8b-4efd-a276-f92aea5880e3
@appointmentId = 3ce0c685-2221-4cb8-9161-5043740ced54
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiNzMxZTBiMy02Mzg0LTRhNTgtODdmNi1hYzFmOTFlYjY4ZWQiLCJyb2xlIjoidmV0ZXJpbmFyaWFuIiwiaWF0IjoxNzc5NzYyMzI1LCJleHAiOjE3Nzk3NjU5MjV9.skRk00TQgPwvOZTUKZxdxwuJxq-9f7NHkSSUqh3zuAA

### --- CITAS (APPOINTMENTS) ---

### Ver calendario de citas
GET {{baseUrl}}/appointments
Content-Type: application/json
Authorization: Bearer {{token}}








### Agendar nueva cita médica
POST {{baseUrl}}/appointments
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "animalId": "{{animalId}}",
    "date": "2026-04-10T10:00:00.000Z",
    "reason": "Revisión general y desparasitación",
    "status": "scheduled"
}








### Cambiar estado de cita (Completada o Cancelada)
PATCH {{baseUrl}}/appointments/{{appointmentId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "status": "completed"
}


### --- HISTORIAL MÉDICO ---

### Ver historial médico completo de un animal
GET {{baseUrl}}/animals/{{animalId}}/history
Content-Type: application/json
Authorization: Bearer {{token}}









### Agregar nueva entrada al historial clínico
POST {{baseUrl}}/animals/{{animalId}}/history
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "date": "2023-10-01T10:00:00.000Z",
    "reason": "Consulta por pérdida de apetito",
    "diagnosis": "Gastritis leve por cambio de alimento",
    "treatment": "Dieta blanda por 3 días y protector gástrico",
    "observations": "El animal se encuentra estable, peso normal."
}







### --- VACUNACIÓN ---

### Ver carnet de vacunación de un animal
GET {{baseUrl}}/animals/{{animalId}}/vaccines
Content-Type: application/json
Authorization: Bearer {{token}}













### Registrar aplicación de una vacuna
POST {{baseUrl}}/animals/{{animalId}}/vaccines
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "vaccineName": "Antirrábica",
    "applicationDate": "2026-03-26T00:00:00.000Z",
    "nextDoseDate": "2027-03-26T00:00:00.000Z",
    "batchNumber": "VAC-12345-XZ"
}
