@baseUrl = http://localhost:3000/api/v1
@animalId = 0d8a9284-eb8b-4efd-a276-f92aea5880e3
@foodId = 3b96556c-6168-4732-b57b-0c00a7377cfe
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YzZlY2I4Zi1hZTdhLTQ0ODItOWZlNS1jNDFkNzI4MDIzY2UiLCJyb2xlIjoiem9vdGVjaG5pY2lhbiIsImlhdCI6MTc3OTc2NTY3OSwiZXhwIjoxNzc5NzY5Mjc5fQ.w3DNsBrWo5VwydOlw4-OVkT95WBfmfY2OI8eJ3V07UQ

### --- NUTRICIÓN E INVENTARIO (FOOD & ALIMENTATION) ---

### Listar todos los alimentos en catálogo
GET {{baseUrl}}/foods
Content-Type: application/json
Authorization: Bearer {{token}}














### Registrar nuevo alimento al catálogo
POST {{baseUrl}}/foods
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Concentrado Premium",
    "description":"delicious",
    "nutritionalValue": "Proteína 20%, Energía Alta",
    "type": "Seco"
}








### Ver registro de alimentación (dieta) de un animal
GET {{baseUrl}}/animals/{{animalId}}/diet
Content-Type: application/json
Authorization: Bearer {{token}}










### Registrar nueva dieta / consumo de alimento para un animal
POST {{baseUrl}}/animals/{{animalId}}/diet
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "foodId": "{{foodId}}",
    "quantity": 2.5,
    "frequency": "daily"
}








### --- PRODUCCIÓN (PRODUCTION) ---

### Ver datos de producción de un animal
GET {{baseUrl}}/animals/{{animalId}}/production
Content-Type: application/json
Authorization: Bearer {{token}}












### Registrar nueva métrica de producción
POST {{baseUrl}}/animals/{{animalId}}/production
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "type": "Leche",
    "quantity": 15.5,
    "unit": "Litros",
    "date": "2026-04-03T00:00:00.000Z",
    "purpose":"milk"
}











### --- REPRODUCCIÓN (REPRODUCTION) ---

### Ver historial reproductivo de un animal
GET {{baseUrl}}/animals/{{animalId}}/reproduction
Content-Type: application/json
Authorization: Bearer {{token}}













### Registrar evento reproductivo
POST {{baseUrl}}/animals/{{animalId}}/reproduction
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "reproductiveStatus":"pregnant",
    "offspringCount":2,
    "breedingType":"natural"
}
