@baseUrl = http://localhost:3000/api/v1
@ownerId = 0f1710ce-7e0b-488a-bfe6-747d936c38e0
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0OWY4MTc1My02MzllLTRjOWQtYmMyNy0xM2I3ZGYzZGJlZDUiLCJyb2xlIjoiYWRtaW5pc3RyYXRvciIsImlhdCI6MTc3OTc2MTA1OSwiZXhwIjoxNzc5NzY0NjU5fQ.lfuEKY7fKsblcQdc9QEL7sXcfs_qU6HLHV2_GAEHT_o

### --- PROPIETARIOS (OWNERS) ---

### Listar todos los propietarios
GET {{baseUrl}}/owners
Content-Type: application/json
Authorization: Bearer {{token}}

### Registrar nuevo propietario
POST {{baseUrl}}/owners
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Luis Miguel",
    "document": "1013113151",
    "phone": "3001234567",
    "email": "juan.perez@example.com",
    "address": "Calle 123 # 45-67",
    "ownerType": "urban" 
}
# ownerType puede ser "urban" o "rural"

### Obtener propietario por ID
GET {{baseUrl}}/owners/{{ownerId}}
Content-Type: application/json
Authorization: Bearer {{token}}

### Actualizar perfil de propietario
PUT {{baseUrl}}/owners/{{ownerId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "phone": "3109876543",
    "email": "juan.perez.new@example.com"
}

### Listar animales de un propietario
GET {{baseUrl}}/owners/{{ownerId}}/animals
Content-Type: application/json
Authorization: Bearer {{token}}

### Eliminar propietario
DELETE {{baseUrl}}/owners/{{ownerId}}
Content-Type: application/json
Authorization: Bearer {{token}}